In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import geopandas as gpd
from shapely.geometry import Point, Polygon, LineString
import seaborn as sns
import pickle
#import descartes
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [ ]:
# Loading the accident data of Seattle city
# the traffic collisions data is 
#found at http://data-seattlecitygis.opendata.arcgis.com/datasets/5b5c745e0f1f48e7a53acec63a0022ab_0

# attributes are found at https://www.seattle.gov/Documents/Departments/SDOT/GIS/Collisions_OD.pdf

acc = gpd.read_file('https://opendata.arcgis.com/datasets/5b5c745e0f1f48e7a53acec63a0022ab_0.geojson')

In [ ]:
# Street network data found 
# at http://data-seattlecitygis.opendata.arcgis.com/datasets/seattle-streets

# this is the street network data in geojson format
#roads = gpd.read_file('https://opendata.arcgis.com/datasets/383027d103f042499693da22d72d10e3_0.geojson')

In [ ]:
#roads = gpd.read_file('https://opendata.arcgis.com/datasets/383027d103f042499693da22d72d10e3_0.geojson')

In [ ]:
roads = gpd.read_file('data/Street_Network_Database_SND.geojson')

In [7]:
roads.head()

,OBJECTID,F_INTR_ID,T_INTR_ID,SND_ID,SND_FEACODE,CITYCODE,STNAME_ID,ST_CODE,ARTERIAL_CODE,SEGMENT_TYPE,...,R_CITY,R_STATE,R_ZIP,SNDSEG_UPDATE,COMPKEY,COMPTYPE,UNITID,UNITID2,SHAPE_Length,geometry
0,6279683,17740,17791,33478,Major Street,Inside Seattle,566,Open Public Street,Arterial,Street,...,SEATTLE,WA,98108,2007-04-22T00:00:00,8460,68,04805,0820,291.426597,LINESTRING (-122.3228596360951 47.529814284070...
1,6279684,11391,11295,20097,Local Street,Inside Seattle,659,Open Public Street,Non-Arterial,Street,...,SEATTLE,WA,98102,2007-04-22T00:00:00,9236,68,05465,0010,431.468071,LINESTRING (-122.3240048069682 47.618483387222...
2,6279685,982,979,42208,Local Street,Outside Seattle,1797,Private Street,Non-Arterial,Street,...,LAKE FOREST PARK,WA,98155,2004-05-19T00:00:00,0,0,0,0,162.445956,LINESTRING (-122.2919134978717 47.764898620027...
3,6279686,11695,11696,20460,"Stairs, Trail, Walkway",Inside Seattle,1444,Stairs,Non-Arterial,Stairs,...,SEATTLE,WA,98122,2004-05-19T00:00:00,0,0,0,0,79.522616,LINESTRING (-122.3078004901454 47.614100270472...
4,6279687,6257,6252,9237,Local Street,Inside Seattle,2086,Open Public Street,Non-Arterial,Street,...,SEATTLE,WA,98107,2012-10-12T00:00:00,18575,68,14630,0200,643.835646,LINESTRING (-122.3821271445327 47.674552340651...

In [9]:
# 2016 Traffic volume data found at https://opendata.arcgis.com/datasets/0dd0ad79dc3845f3a296215d7c448a0d_2.geojson

# this is the traffic volume data per road segment
traffic = gpd.read_file('https://opendata.arcgis.com/datasets/170b764c52f34c9497720c0463f3b58b_9.geojson')

In [1]:
traffic.head()

NameError: name 'traffic' is not defined

In [18]:
#traffic = gpd.read_file('https://opendata.arcgis.com/datasets/383027d103f042499693da22d72d10e3_0.geojson')

In [6]:
roads.columns

Index(['OBJECTID', 'F_INTR_ID', 'T_INTR_ID', 'SND_ID', 'SND_FEACODE',
       'CITYCODE', 'STNAME_ID', 'ST_CODE', 'ARTERIAL_CODE', 'SEGMENT_TYPE',
       'AGENCY_CODE', 'ACCESS_CODE', 'DIVIDED_CODE', 'STRUCTURE_TYPE',
       'LEGALLOC_CODE', 'VEHICLE_USE_CODE', 'GIS_SEG_LENGTH', 'L_ADRS_FROM',
       'L_ADRS_TO', 'R_ADRS_FROM', 'R_ADRS_TO', 'ORD_PRE_DIR',
       'ORD_STREET_NAME', 'ORD_STREET_TYPE', 'ORD_SUF_DIR',
       'ORD_STNAME_CONCAT', 'L_CITY', 'L_STATE', 'L_ZIP', 'R_CITY', 'R_STATE',
       'R_ZIP', 'SNDSEG_UPDATE', 'COMPKEY', 'COMPTYPE', 'UNITID', 'UNITID2',
       'SHAPE_Length', 'geometry'],
      dtype='object')

In [9]:
acc.head()

,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,LOCATION,EXCEPTRSNCODE,EXCEPTRSNDESC,...,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR,geometry
0,1,300647,301861,E828639,Matched,Block,NaN,WEEDIN E PL NE BETWEEN WEEDIN PL NE AND 8TH AV...,,None,...,Daylight,None,None,None,10,Entering at angle,0,0,N,POINT (-122.3194826900306 47.67599681324806)
1,2,300655,301869,3626843,Matched,Block,NaN,OLSON PL SW BETWEEN 1ST AVE S AND 2ND AVE SW,,None,...,Daylight,None,None,None,14,From same direction - both going straight - on...,0,0,N,POINT (-122.3355699288946 47.5217841204985)
2,3,300644,301858,E828638,Matched,Intersection,27031.0,TROLL AVE N AND N 36TH ST,,None,...,Daylight,None,None,None,32,One parked--one moving,0,0,Y,POINT (-122.3473968315823 47.65096640309453)
3,4,300662,301876,3705919,Matched,Intersection,29080.0,FRANKLIN AVE E AND E GALER ST,,None,...,Unknown,None,None,None,32,One parked--one moving,0,0,Y,POINT (-122.3249560537502 47.63225641102942)
4,5,300650,301864,3206769,Matched,Intersection,28403.0,24TH AVE E AND E MILLER ST,,None,...,Daylight,None,None,None,14,From same direction - both going straight - on...,0,0,N,POINT (-122.3020586455341 47.64171802992309)